# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
    - label: Home
      title: Back to the home page.
      path: homepage
      class: first
    - label: About
      path: page/about
    - label: Artists
      path: artists/
    - label: Releases
      path: releases
    - label: Events
      path: events
    - label: Decoration
      path: page/decoration
      class: last
